# see https://github.com/ELIXIR-Belgium/elixir-toolkit-theme
title: "BioCommons Nextflow Tower"
description: A website for the Tower service
remote_theme: ELIXIR-Belgium/jekyll-bootstrap-theme@1.20.2
topnav_title: Tower

theme_variables:
  # biocommons blue
  theme_color: 205a86
  topnav:
    brand_logo: assets/img/main_logo.png
  privacy_statement_url: https://www.biocommons.org.au/privacy

permalink: /:categories/:year/:month/:day/:title

exclude:
  - README.md

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      sidebar: main
